// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF2cnK5lSOxoS37Os5GtCFR_gvf-nkxl0',
    appId: '1:41692962765:web:c4224e3c7cadd784996e84',
    messagingSenderId: '41692962765',
    projectId: 'theras-c95da',
    authDomain: 'theras-c95da.firebaseapp.com',
    databaseURL: 'https://theras-c95da-default-rtdb.firebaseio.com',
    storageBucket: 'theras-c95da.appspot.com',
    measurementId: 'G-TJ9D8FDMM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIKlMCoNmxbToV_DzPyAH9t8JIHoFC6FI',
    appId: '1:41692962765:android:913b86544768abda996e84',
    messagingSenderId: '41692962765',
    projectId: 'theras-c95da',
    databaseURL: 'https://theras-c95da-default-rtdb.firebaseio.com',
    storageBucket: 'theras-c95da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIX3BRceBDtlTzHKpin-4iQpGTwSBScRg',
    appId: '1:41692962765:ios:ccb866c8c0322195996e84',
    messagingSenderId: '41692962765',
    projectId: 'theras-c95da',
    databaseURL: 'https://theras-c95da-default-rtdb.firebaseio.com',
    storageBucket: 'theras-c95da.appspot.com',
    iosBundleId: 'com.example.therasApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIX3BRceBDtlTzHKpin-4iQpGTwSBScRg',
    appId: '1:41692962765:ios:782338f2a1d12944996e84',
    messagingSenderId: '41692962765',
    projectId: 'theras-c95da',
    databaseURL: 'https://theras-c95da-default-rtdb.firebaseio.com',
    storageBucket: 'theras-c95da.appspot.com',
    iosBundleId: 'com.example.therasApp.RunnerTests',
  );
}
